Repository parallaxsecond/rust-tss-esapi, pull requests merged in 2019-12, with the labels that each got.

#5 Add a CI job for tests with TPM simulation server
  .github/workflows/ci.yml
  src/lib.rs
  tests/Dockerfile
  tests/all.sh
Labels: enhancement

#4 Add transient object context
  src/abstraction/mod.rs
  src/abstraction/transitory.rs
  src/lib.rs
  src/utils.rs
  tests/all.sh
Labels: enhancement

#11 Fix various issues
  .gitignore
  Cargo.toml
  src/abstraction/mod.rs
  src/abstraction/transient.rs
  src/lib.rs
Labels: bug, enhancement

#12 Fix session handling
  Cargo.toml
  src/abstraction/transient.rs
  src/response_code.rs
Labels: bug

#16 Add pkg-config in the build script
  Cargo.toml
  README.md
  build.rs
  tests/Dockerfile
Labels: bug

#15 Add wrapper crate-specific errors
  src/abstraction/transient.rs
  src/lib.rs
  src/response_code.rs
  src/utils.rs
Labels: enhancement

#17 Improve usage of unwrap and expect
  src/abstraction/transient.rs
  src/lib.rs
  src/response_code.rs
  src/utils.rs
Labels: bug, enhancement

#18 Improve usage of unsafe blocks
  src/abstraction/transient.rs
  src/lib.rs
  src/utils.rs
Labels: bug, enhancement

#19 Improve TransientObjectContext interface
  src/abstraction/transient.rs
  src/utils.rs
Labels: enhancement
