Repository parallaxsecond/rust-tss-esapi, pull requests merged in 2020-05, with the labels that each got.

#67 Refactor `Cipher`; Add `quote` method
  Cargo.toml
  README.md
  src/constants.rs
  src/lib.rs
  src/utils/algorithm_specifiers.rs
  tests/context_tests.rs
Labels: bug, enhancement

#69 Add support for elliptic curves for transient context
  .gitignore
  Cargo.toml
  src/abstraction/transient.rs
  src/utils/algorithm_specifiers.rs
  src/utils/mod.rs
  tests/context_tests.rs
  tests/transient_key_context.rs
Labels: enhancement

#70 Fix ECDSA signature variant name
  Cargo.toml
  src/utils/mod.rs
Labels: bug

#72 Hash method
  src/abstraction/transient.rs
  src/constants.rs
  src/lib.rs
  src/utils/mod.rs
  src/utils/tags.rs
  src/utils/tickets.rs
  tests/context_tests.rs
Labels: enhancement

#74 Also add the TSS2-MU library
  build.rs
Labels: enhancement
