Repository parallaxsecond/rust-tss-esapi, pull requests merged in 2020-01, with the labels that each got.

#20 Add documentation
  src/abstraction/transient.rs
  src/lib.rs
  src/response_code.rs
  src/utils.rs
  tests/all.sh
Labels: documentation

#22 Deny compilation to chosen rustc lints
  Cargo.toml
  src/abstraction/transient.rs
  src/lib.rs
  src/utils.rs
Labels: enhancement

#25 Add integration tests
  src/lib.rs
  tests/context_tests.rs
Labels: enhancement

#26 Add TransientObjectContext integration tests
  src/abstraction/transient.rs
  tests/all.sh
  tests/transient_object_context.rs
Labels: enhancement

#27 Add multithreading docs
  Cargo.toml
  src/abstraction/transient.rs
  src/lib.rs
  tests/context_tests.rs
  tests/transient_object_context.rs
Labels: documentation

#29 Fix clippy warnings
  src/abstraction/transient.rs
  src/lib.rs
  tests/all.sh
  tests/context_tests.rs
  tests/transient_object_context.rs
Labels: documentation, enhancement

#28 Adding metadata and bumping to 1.0.0
  Cargo.toml
Labels: documentation

#32 Improve docs
  Cargo.toml
  README.md
  build.rs
  doc_bindings.rs
  src/lib.rs
Labels: documentation

#33 Remove 'unimplemented' use and fix lints
  Cargo.toml
  src/abstraction/transient.rs
  src/lib.rs
  src/response_code.rs
  src/utils.rs
Labels: enhancement
