Repository parallaxsecond/rust-tss-esapi, pull requests merged in 2021-03, with the labels that each got.

#196 Add code coverage reporting
  .github/workflows/nightly.yml
  tss-esapi/tests/coverage.sh
Labels: enhancement

#203 Make codecov recognize environment
  .github/workflows/nightly.yml
  tss-esapi/tests/coverage.sh
Labels: bug

#201 This is an attempt to fix tests that fails locally.
  tss-esapi/src/abstraction/transient.rs
  tss-esapi/tests/context_tests/tpm_commands/enhanced_authorization_ea_commands_tests.rs
  tss-esapi/tests/context_tests/tpm_commands/object_commands_tests.rs
  tss-esapi/tests/context_tests/tpm_commands/random_number_generator_tests.rs
Labels: enhancement

#205 Update registry for Dockerfiles
  tss-esapi/tests/Dockerfile-ubuntu
Labels: bug

#195 Changed Session into an interface type.
  tss-esapi/src/abstraction/ak.rs
  tss-esapi/src/abstraction/transient.rs
  tss-esapi/src/context.rs
  tss-esapi/src/context/session_administration.rs
  tss-esapi/src/context/tpm_commands/context_management.rs
  tss-esapi/src/context/tpm_commands/enhanced_authorization_ea_commands.rs
  tss-esapi/src/context/tpm_commands/session_commands.rs
  tss-esapi/src/interface_types/mod.rs
  tss-esapi/src/interface_types/session_handles.rs
  tss-esapi/src/lib.rs
  tss-esapi/src/session.rs
  tss-esapi/src/session/specific.rs
  tss-esapi/tests/abstraction_ak_tests.rs
  tss-esapi/tests/common/mod.rs
  tss-esapi/tests/context_tests/general_esys_tr_tests.rs
  tss-esapi/tests/context_tests/tpm_commands/enhanced_authorization_ea_commands_tests.rs
  tss-esapi/tests/context_tests/tpm_commands/session_commands_tests.rs
Labels: bug, enhancement

#209 Fix cross-compile permissions
  tss-esapi/tests/cross-compile.sh
Labels: bug

#212 Fix cross-compilation scripts
  tss-esapi-sys/build.rs
  tss-esapi-sys/src/bindings/arm-unknown-linux-gnueabi.rs
  tss-esapi-sys/src/lib.rs
  tss-esapi/tests/cross-compile.sh
  tss-esapi/tests/pkg-config
Labels: bug

#215 Fix a failing bindgen test
  tss-esapi-sys/build.rs
Labels: bug
